Repository knative-extensions/func-python, pull requests merged in 2024-12, with the labels that each got.

#21 Add initial test suite
  README.md
  poetry.lock
  pyproject.toml
  src/func_python/http.py
  tests/test_http.py
Labels: lgtm, approved, size/L

#22 Using Env_vars for starting the server, avoind hard coded address all over the place
  tests/test_http.py
Labels: lgtm, approved, size/S

#25 Updating info on the py project file
  pyproject.toml
Labels: size/XS, lgtm, approved

#26 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
