Repository knative-extensions/func-python, pull requests merged in 2024-11, with the labels that each got.

#17 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#18 Message returns
  README.md
  cmd/fhttp/main.py
  src/func_python/http.py
Labels: size/M, lgtm, approved

#19 Release v0.2.0
  CHANGELOG.md
  pyproject.toml
Labels: lgtm, approved, size/S

#20 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review
