Repository knative-extensions/func-python, pull requests merged in 2024-10, with the labels that each got.

#10 Remove extra line (more to test prow again)
  README.md
Labels: size/XS, lgtm, approved

#11 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#12 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#13 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#14 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#15 add publish workflows
  .github/workflows/publish.yaml
  CHANGELOG.md
Labels: lgtm, approved, size/L

#16 Release v0.1.0
  CHANGELOG.md
Labels: size/XS, lgtm, approved
