Repository knative-extensions/func-python, pull requests merged in 2024-09, with the labels that each got.

#1 initial ASGI implementation
  http/serve.py
Labels: lgtm, approved, size/L

#3 [main] Update actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: size/L, skip-review

#5 chore: module and dependencies
  __init__.py
  http/__init__.py
  http/requirements.txt
Labels: size/XS, lgtm, approved

#6 chore: initial documentation
  cmd/fhttp/README.md
  http/README.md
Labels: size/M, kind/documentation, lgtm, approved

#7 feat: setup with poetry
  .gitignore
  README.md
  cmd/fhttp/README.md
  cmd/fhttp/main.py
  http/__init__.py
  http/requirements.txt
  poetry.lock
  pyproject.toml
  src/func_python/README.md
  src/func_python/__init__.py
  src/func_python/http.py
Labels: lgtm, approved, size/L

#9 feat: make Function an ASGI callable
  cmd/fhttp/main.py
  src/func_python/http.py
Labels: size/M, lgtm, approved
