Repository knative-extensions/func-python, pull requests merged in 2025-01, with the labels that each got.

#27 WIP: Adding some signal handling
  src/func_python/http.py
  tests/test_http.py
Labels: size/M, lgtm, approved

#28 Adding on_stop lifecycle handler
  cmd/fhttp/main.py
Labels: size/XS, lgtm, approved

#30 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#29 Replace typo in comment
  cmd/fhttp/main.py
  src/func_python/http.py
Labels: size/XS, lgtm, approved

#31 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#32 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#33 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
