Repository knative-extensions/func-python, pull requests merged in 2025-03, with the labels that each got.

#40 Release v0.4.0
  CHANGELOG.md
  README.md
Labels: lgtm, approved

#41 chore: update legacy test pypi action url
  .github/workflows/publish.yaml
Labels: lgtm, approved

#42 chore: update github cli on publish action
  .github/workflows/publish.yaml
Labels: size/XS, lgtm, approved

#43 Release v0.4.1
  CHANGELOG.md
  pyproject.toml
Labels: size/XS, lgtm, approved

#44 Update Sigstore used in Actions
  .github/workflows/publish.yaml
  CHANGELOG.md
Labels: lgtm, approved, size/S

#45 Release v0.4.2
  pyproject.toml
Labels: lgtm, approved

#46 Downgrade python requirement to support latest S2I
  CHANGELOG.md
  README.md
  poetry.lock
  pyproject.toml
Labels: kind/cleanup, lgtm, approved, size/L

#47 fix CloudEvent raw http response
  CHANGELOG.md
  README.md
  src/func_python/cloudevent.py
Labels: kind/bug, lgtm, approved, size/S

#48 Release v0.5.0
  CHANGELOG.md
Labels: lgtm, approved, size/S

#49 Release v0.5.1
  CHANGELOG.md
  pyproject.toml
Labels: size/XS, lgtm, approved

#50 Adding initial/simple CE function
  cmd/fcloudevent/README.md
  cmd/fcloudevent/main.py
Labels: lgtm, approved, size/L

#51 Polish README.md files a bit
  README.md
  cmd/fcloudevent/README.md
  cmd/fhttp/README.md
Labels: size/M, lgtm, approved

#52 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
