Repository knative-extensions/func-python, pull requests merged in 2025-02, with the labels that each got.

#34 Improved cross-language homogeneity
  CHANGELOG.md
  cmd/fhttp/main.py
  src/func_python/http.py
  tests/test_http.py
Labels: size/M, lgtm, approved

#35 Update changelog
  CHANGELOG.md
Labels: size/XS, lgtm, approved

#36 Release v0.3.0
  CHANGELOG.md
  pyproject.toml
Labels: lgtm, approved, size/S

#37 release and test instructions
  README.md
Labels: lgtm, approved

#38 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
